# Generated by Django 4.0.2 on 2022-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('spends', models.FloatField()),
                ('mode', models.TextField()),
                ('purpose', models.TextField()),
                ('quarter', models.TextField()),
                ('country', models.TextField()),
                ('prediction', models.IntegerField()),
            ],
        ),
    ]
