version: '3.4'

services:
  deploymentlearning_database:
    image: tourist_db:deploy_db
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
        sh -c "sleep 20 &&
                python manage.py migrate --noinput && 
                gunicorn --bind 0.0.0.0:8001 ttps.wsgi:application"
    ports:
      - 8001:8001
    depends_on:
      - db
    container_name: application

    
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data:rw
    container_name: database

volumes:
     data:
    